name: Issue Milestone Assigner
permissions:
   issues: write
   contents: read

on:
   issues:
      types: [opened, edited]

jobs:
   assign-milestone:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Assign Milestone to Issue
           uses: actions/github-script@v6
           with:
              script: |
                 const assignMilestone = require('./.github/scripts/assign-milestone.js');
                 await assignMilestone({ github, context });
              github-token: ${{ secrets.GITHUB_TOKEN }}

         - name: Assign Issue to Project
           uses: actions/github-script@v6
           with:
              script: |
                 const assignToProject = require('./.github/scripts/assign-to-project.js');
                 await assignToProject({ github, context, columnId: 1 });
              github-token: ${{ secrets.GITHUB_TOKEN }}
